Added REST API
KaneDenzil/IIM-Lucknow-Landing-Page pull request #1
Opened 2022-01-06 16:23 UTC by sheikhuzairhussain

2022-01-06 16:56 UTC, KaneDenzil requested changes
Please let me know about the questions

2022-01-06 16:56 UTC, KaneDenzil commented on api/index.js
> +        message: "Application submitted successfully.",
It'll be great if you send an error code so when the FrontEnd compares the response we can use the error code as comparison

2022-01-06 16:56 UTC, KaneDenzil commented on api/index.js
> +    ]);
How do you handle if any of the field is empty or if the type of the field is invalid

2022-01-06 17:12 UTC, sheikhuzairhussain commented on api/index.js
> +    ]);
This is just a barebones implementation of the idea we discussed. I will be adding proper validation and error handling over the next few commits.

2022-01-07 01:53 UTC, KaneDenzil commented on api/index.js
> +    ]);
Sounds good

2022-01-07 01:54 UTC, merged